# Task 2: SQL & Python Integration

## ApexPlanet Data Analytics Internship

### Name: Pavani
### Dataset: SuperMarket Analysis

In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [4]:
import pandas as pd
import sys
import os

sys.path.append(os.path.abspath("../scripts"))

from db_utils import get_connection

engine = get_connection()

In [5]:
query = """
SELECT * FROM sales
LIMIT 5;
"""

df = pd.read_sql(query, engine)

df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [6]:
query = """
SELECT SUM(`Sales`) AS Total_Sales
FROM sales;
"""

pd.read_sql(query, engine)

   Total_Sales
0   322966.749

In [7]:
query = """
SELECT Branch,
SUM(`Sales`) AS Total_Sales
FROM sales
GROUP BY Branch;
"""

pd.read_sql(query, engine)

  Branch  Total_Sales
0   Alex  106200.3705
1   Giza  110568.7065
2  Cairo  106197.6720

In [8]:
query = """
SELECT City,
SUM(`Sales`) AS Total_Sales
FROM sales
GROUP BY City;
"""

pd.read_sql(query, engine)

        City  Total_Sales
0     Yangon  106200.3705
1  Naypyitaw  110568.7065
2   Mandalay  106197.6720

In [10]:
query = """
SELECT `Product line`,
SUM(`Sales`) AS Total_Sales
FROM sales
GROUP BY `Product line`;
"""

pd.read_sql(query, engine)

             Product line  Total_Sales
0       Health and beauty   49193.7390
1  Electronic accessories   54337.5315
2      Home and lifestyle   53861.9130
3       Sports and travel   55122.8265
4      Food and beverages   56144.8440
5     Fashion accessories   54305.8950

In [11]:
query = """
SELECT `Product line`,
AVG(Rating) AS Average_Rating
FROM sales
GROUP BY `Product line`
ORDER BY Average_Rating DESC;
"""

pd.read_sql(query, engine)

             Product line  Average_Rating
0      Food and beverages        7.113218
1     Fashion accessories        7.029213
2       Health and beauty        7.003289
3  Electronic accessories        6.924706
4       Sports and travel        6.916265
5      Home and lifestyle        6.837500

In [12]:
query = """
SELECT `Invoice ID`,
`Sales`
FROM sales
ORDER BY `Sales` DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

    Invoice ID     Sales
0  860-79-0874  1042.650
1  687-47-8271  1039.290
2  283-26-5248  1034.460
3  751-41-9720  1023.750
4  303-96-2227  1022.490
5  744-16-7898  1022.385
6  271-88-8734  1020.705
7  234-65-2137  1003.590
8  554-42-2417  1002.120
9  325-77-6186   951.825

In [13]:
query = """
SELECT *
FROM sales
WHERE `Sales` >
(
    SELECT AVG(`Sales`)
    FROM sales
);
"""

pd.read_sql(query, engine)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
2,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
3,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
4,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
400,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
401,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
402,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
403,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [14]:
query = """
SELECT
    `Invoice ID`,
    `Sales`,
    RANK() OVER (ORDER BY `Sales` DESC) AS Sales_Rank
FROM sales;
"""

pd.read_sql(query, engine)

      Invoice ID      Sales  Sales_Rank
0    860-79-0874  1042.6500           1
1    687-47-8271  1039.2900           2
2    283-26-5248  1034.4600           3
3    751-41-9720  1023.7500           4
4    303-96-2227  1022.4900           5
..           ...        ...         ...
995  236-86-3015    14.6790         996
996  192-98-7397    13.4190         997
997  279-62-1445    13.1670         998
998  308-39-1707    12.6945         999
999  784-21-9238    10.6785        1000

[1000 rows x 3 columns]

# Conclusion

- Successfully connected Python with MySQL using SQLAlchemy.
- Imported and queried the SuperMarket Analysis dataset.
- Executed SQL operations including filtering, aggregation, GROUP BY, HAVING, subqueries, and window functions.
- Retrieved query results directly into Python using pandas.
- Completed Task 2: SQL for Data Analysis.